# Practice Project: GDP Data extraction and processing



## Introduction

In this practice project, I will extract data from a website using webscraping and reqeust APIs process it using Pandas and Numpy libraries.

## Project Scenario:

An international firm that is looking to expand its business in different countries across the world has recruited you. You have been hired as a junior Data Engineer and are tasked with creating a script that can extract the list of the top 10 largest economies of the world in descending order of their GDPs in Billion USD (rounded to 2 decimal places), as logged by the International Monetary Fund (IMF). 

The required data seems to be available on the URL mentioned below:

URL: https://web.archive.org/web/20230902185326/https://en.wikipedia.org/wiki/List_of_countries_by_GDP_%28nominal%29

---

In [2]:
import numpy as np
import pandas as pd

# You can also use this section to suppress warnings generated by your code:
def warn(*args, **kwargs):
    pass
import warnings
warnings.warn = warn
warnings.filterwarnings('ignore')

---

# Exercises

### Exercise 1
Extract the required GDP data from the given URL using Web Scraping.

In [ ]:
URL="https://web.archive.org/web/20230902185326/https://en.wikipedia.org/wiki/List_of_countries_by_GDP_%28nominal%29"

You can use Pandas library to extract the required table directly as a DataFrame. Note that the required table is the third one on the website, as shown in the image below.

<img src="https://cf-courses-data.s3.us.cloud-object-storage.appdomain.cloud/IBMDeveloperSkillsNetwork-PY0101EN-SkillsNetwork/images/pandas_wbs_3.png">

In [4]:
URL = "https://web.archive.org/web/20230902185326/https://en.wikipedia.org/wiki/List_of_countries_by_GDP_%28nominal%29"

# Extracting tables from the webpage
tables = pd.read_html(URL)

# Retaining table number 3
df = tables[3]

# Replacing column headers with column numbers
df.columns = range(df.shape[1])

# Retained columns 0 and 2
df = df[[0, 2]]

# Retain rows 1 to 10
df = df.iloc[1:11]

# Assign column names
df.columns = ["Country", "GDP (Million USD)"]

# Display the dataframe
df

           Country GDP (Million USD)
1    United States          26854599
2            China          19373586
3            Japan           4409738
4          Germany           4308854
5            India           3736882
6   United Kingdom           3158938
7           France           2923489
8            Italy           2169745
9           Canada           2089672
10          Brazil           2081235

### Exercise 2
Modify the GDP column of the DataFrame, converting the value available in Million USD to Billion USD. Use the `round()` method of Numpy library to round the value to 2 decimal places. Modify the header of the DataFrame to `GDP (Billion USD)`.

In [5]:
# Changing the data type of the 'GDP (Million USD)' column to integer
df["GDP (Million USD)"] = df["GDP (Million USD)"].astype(int)

# Converting GDP from Million USD to Billion USD
df["GDP (Million USD)"] = df["GDP (Million USD)"] / 1000

# Round the values to 2 decimal places
df["GDP (Million USD)"] = np.round(df["GDP (Million USD)"], 2)

# Rename the column
df.rename(columns={"GDP (Million USD)": "GDP (Billion USD)"}, inplace=True)

# Display the dataframe
df

           Country  GDP (Billion USD)
1    United States           26854.60
2            China           19373.59
3            Japan            4409.74
4          Germany            4308.85
5            India            3736.88
6   United Kingdom            3158.94
7           France            2923.49
8            Italy            2169.74
9           Canada            2089.67
10          Brazil            2081.24

### Exercise 3

Load the DataFrame to the CSV file named "Largest_economies.csv"

In [8]:
# Load the DataFrame to the CSV file named "Largest_economies.csv"
df.to_csv("Largest_economies.csv", index=False)